extends RefCounted
class_name StratagemData
## 战备数据类

## 指令箭头方向的易读对应枚举
enum CodeArrow{
	UP,
	DOWN,
	LEFT,
	RIGHT,
}
## 战备类型
enum StratagemClass{
	SUPPORT = 1, # 支援
	ATTACK = 2, # 攻击
	DEFENCE = 3, # 防御
	COMMON = 0, # 通用
}

## 战备的图标
var icon: Texture2D
## 战备的翻译键名
var name_key: String
## 战备指令列表
var codes: Array[CodeArrow]
## 所属的战备类型
var stratagem_class: StratagemClass
## 记录本战备是否属于债券战备
var is_in_warbonds: bool

func _init(new_icon: Texture2D, new_name_key: String, new_codes: String, new_class: StratagemClass, new_in_warbonds: bool) -> void:
	icon = new_icon
	name_key = new_name_key
	set_codes_by_string(new_codes)
	stratagem_class = new_class
	is_in_warbonds = new_in_warbonds

## 以字符串的形式设定指令，可接受这四种字符：< ^ > v
func set_codes_by_string(string: String) -> void:
	codes = []
	for current_char in string:
		match (current_char):
			"<":
				codes.append(CodeArrow.LEFT)
			"^":
				codes.append(CodeArrow.UP)
			">":
				codes.append(CodeArrow.RIGHT)
			"v":
				codes.append(CodeArrow.DOWN)

## 记录所有战备数据的列表
static var list: Dictionary[StringName, StratagemData]:
	get:
		return {
			&"airburst_rocket_launcher":
				StratagemData.new(
					preload("res://resources/images/airburst_rocket_launcher.svg"),
					"stratagem_name.airburst_rocket_launcher",
					"v^^<>",
					StratagemClass.SUPPORT,
					false
				),
			&"anti_materiel_rifle":
				StratagemData.new(
					preload("res://resources/images/anti_materiel_rifle.svg"),
					"stratagem_name.anti_materiel_rifle",
					"v<>^v",
					StratagemClass.SUPPORT,
					false
				),
			&"anti_personnel_minefield":
				StratagemData.new(
					preload("res://resources/images/anti_personnel_minefield.svg"),
					"stratagem_name.anti_personnel_minefield",
					"v<^>",
					StratagemClass.DEFENCE,
					false
				),
			&"anti_tank_emplacement":
				StratagemData.new(
					preload("res://resources/images/anti_tank_emplacement.svg"),
					"stratagem_name.anti_tank_emplacement",
					"v^<>>>",
					StratagemClass.DEFENCE,
					true
				),
			&"anti_tank_mines":
				StratagemData.new(
					preload("res://resources/images/anti_tank_mines.svg"),
					"stratagem_name.anti_tank_mines",
					"v<^^",
					StratagemClass.DEFENCE,
					false
				),
			&"arc_thrower":
				StratagemData.new(
					preload("res://resources/images/arc_thrower.svg"),
					"stratagem_name.arc_thrower",
					"v>v^<<",
					StratagemClass.SUPPORT,
					false
				),
			&"autocannon":
				StratagemData.new(
					preload("res://resources/images/autocannon.svg"),
					"stratagem_name.autocannon",
					"v<v^^>",
					StratagemClass.SUPPORT,
					false
				),
			&"autocannon_sentry":
				StratagemData.new(
					preload("res://resources/images/autocannon_sentry.svg"),
					"stratagem_name.autocannon_sentry",
					"v^>^<^",
					StratagemClass.DEFENCE,
					false
				),
			&"ballistic_shield_backpack":
				StratagemData.new(
					preload("res://resources/images/ballistic_shield_backpack.svg"),
					"stratagem_name.ballistic_shield_backpack",
					"v<vv^<",
					StratagemClass.SUPPORT,
					false
				),
			&"cargo_container":
				StratagemData.new(
					preload("res://resources/images/cargo_container.svg"),
					"stratagem_name.cargo_container",
					"^^vv>v",
					StratagemClass.COMMON,
					false
				),
			&"commando":
				StratagemData.new(
					preload("res://resources/images/commando.svg"),
					"stratagem_name.commando",
					"v<^v>",
					StratagemClass.SUPPORT,
					false
				),
			&"dark_fluid_vessel":
				StratagemData.new(
					preload("res://resources/images/dark_fluid_vessel.svg"),
					"stratagem_name.dark_fluid_vessel",
					"^<>v^^",
					StratagemClass.COMMON,
					false
				),
			&"defoliation_tool":
				StratagemData.new(
					preload("res://resources/images/defoliation_tool.svg"),
					"stratagem_name.defoliation_tool",
					"v<>>v",
					StratagemClass.SUPPORT,
					true  # TX-41 Sterilizer
				),
			&"directional_shield":
				StratagemData.new(
					preload("res://resources/images/directional_shield.svg"),
					"stratagem_name.directional_shield",
					"v^<>^^",
					StratagemClass.SUPPORT,
					true  # SH-51 Directional Shield
				),
			&"eagle_110mm_rocket_pods":
				StratagemData.new(
					preload("res://resources/images/eagle_110mm_rocket_pods.svg"),
					"stratagem_name.eagle_110mm_rocket_pods",
					"^>^<",
					StratagemClass.ATTACK,
					false
				),
			&"eagle_500kg_bomb":
				StratagemData.new(
					preload("res://resources/images/eagle_500kg_bomb.svg"),
					"stratagem_name.eagle_500kg_bomb",
					"^>vvv",
					StratagemClass.ATTACK,
					false
				),
			&"eagle_airstrike":
				StratagemData.new(
					preload("res://resources/images/eagle_airstrike.svg"),
					"stratagem_name.eagle_airstrike",
					"^>v>",
					StratagemClass.ATTACK,
					false
				),
			&"eagle_cluster_bomb":
				StratagemData.new(
					preload("res://resources/images/eagle_cluster_bomb.svg"),
					"stratagem_name.eagle_cluster_bomb",
					"^>vv>",
					StratagemClass.ATTACK,
					false
				),
			&"eagle_napalm_airstrike":
				StratagemData.new(
					preload("res://resources/images/eagle_napalm_airstrike.svg"),
					"stratagem_name.eagle_napalm_airstrike",
					"^>V^",
					StratagemClass.ATTACK,
					false
				),
			&"eagle_rearm":
				StratagemData.new(
					preload("res://resources/images/eagle_rearm.svg"),
					"stratagem_name.eagle_rearm",
					"^^<^>",
					StratagemClass.COMMON,
					false
				),
			&"eagle_smoke_strike":
				StratagemData.new(
					preload("res://resources/images/eagle_smoke_strike.svg"),
					"stratagem_name.eagle_smoke_strike",
					"^>^v",
					StratagemClass.ATTACK,
					false
				),
			&"eagle_strafing_run":
				StratagemData.new(
					preload("res://resources/images/eagle_strafing_run.svg"),
					"stratagem_name.eagle_strafing_run",
					"^>>",
					StratagemClass.ATTACK,
					false
				),
			&"emancipator_exosuit":
				StratagemData.new(
					preload("res://resources/images/emancipator_exosuit.svg"),
					"stratagem_name.emancipator_exosuit",
					"<v>^<v^",
					StratagemClass.SUPPORT,
					false
				),
			&"ems_mortar_sentry":
				StratagemData.new(
					preload("res://resources/images/ems_mortar_sentry.svg"),
					"stratagem_name.ems_mortar_sentry",
					"v^>v>",
					StratagemClass.DEFENCE,
					false
				),
			&"epoch":
				StratagemData.new(
					preload("res://resources/images/epoch.svg"),
					"stratagem_name.epoch",
					"v<^<>",
					StratagemClass.SUPPORT,
					true  # PLAS-45 Epoch
				),
			&"expendable_anti_tank":
				StratagemData.new(
					preload("res://resources/images/expendable_anti_tank.svg"),
					"stratagem_name.expendable_anti_tank",
					"vv<^>",
					StratagemClass.SUPPORT,
					false
				),
			&"expendable_napalm":
				StratagemData.new(
					preload("res://resources/images/expendable_napalm.svg"),
					"stratagem_name.expendable_napalm",
					"vv<^<",
					StratagemClass.SUPPORT,
					true  # EAT-700 Expendable Napalm
				),
			&"fast_recon_vehicle":
				StratagemData.new(
					preload("res://resources/images/fast_recon_vehicle.svg"),
					"stratagem_name.fast_recon_vehicle",
					"<v>v>v^",
					StratagemClass.SUPPORT,
					false
				),
			&"flame_sentry":
				StratagemData.new(
					preload("res://resources/images/flame_sentry.svg"),
					"stratagem_name.flame_sentry",
					"v^>v^^",
					StratagemClass.DEFENCE,
					true  # A/FLM-40 Flame Sentry
				),
			&"flamethrower":
				StratagemData.new(
					preload("res://resources/images/flamethrower.svg"),
					"stratagem_name.flamethrower",
					"v<^v^",
					StratagemClass.SUPPORT,
					false
				),
			&"gas_mine":
				StratagemData.new(
					preload("res://resources/images/gas_mine.svg"),
					"stratagem_name.gas_mine",
					"v<<>",
					StratagemClass.DEFENCE,
					false
				),
			&"gatling_sentry":
				StratagemData.new(
					preload("res://resources/images/gatling_sentry.svg"),
					"stratagem_name.gatling_sentry",
					"v^><",
					StratagemClass.DEFENCE,
					false
				),
			&"gl_52_de_escalator":
				StratagemData.new(
					preload("res://resources/images/gl_52_de_escalator.svg"),
					"stratagem_name.gl_52_de_escalator",
					"v>^<>",
					StratagemClass.SUPPORT,
					true  # GL-52 De-Escalator
				),
			&"grenade_launcher":
				StratagemData.new(
					preload("res://resources/images/grenade_launcher.svg"),
					"stratagem_name.grenade_launcher",
					"v<^<v",
					StratagemClass.SUPPORT,
					false
				),
			&"grenadier_battlement":
				StratagemData.new(
					preload("res://resources/images/grenadier_battlement.svg"),
					"stratagem_name.grenadier_battlement",
					"v>v<>",
					StratagemClass.DEFENCE,
					false
				),
			&"guard_dog":
				StratagemData.new(
					preload("res://resources/images/guard_dog.svg"),
					"stratagem_name.guard_dog",
					"v^<^>v",
					StratagemClass.SUPPORT,
					false
				),
			&"guard_dog_breath":
				StratagemData.new(
					preload("res://resources/images/guard_dog_breath.svg"),
					"stratagem_name.guard_dog_breath",
					"v^<^>^",
					StratagemClass.SUPPORT,
					true  # AX/TX-13 "Guard Dog" Dog Breath
				),
			&"guard_dog_hot_dog":
				StratagemData.new(
					preload("res://resources/images/guard_dog_hot_dog.svg"),
					"stratagem_name.guard_dog_hot_dog",
					"v^<^<<",
					StratagemClass.SUPPORT,
					true  # AX/FLAM-75 "Guard Dog" Hot Dog
				),
			&"guard_dog_k_9":
				StratagemData.new(
					preload("res://resources/images/guard_dog_k_9.svg"),
					"stratagem_name.guard_dog_k_9",
					"v^<^><",
					StratagemClass.SUPPORT,
					true  # AX/ARC-3 "Guard Dog" K-9
				),
			&"guard_dog_rover":
				StratagemData.new(
					preload("res://resources/images/guard_dog_rover.svg"),
					"stratagem_name.guard_dog_rover",
					"v^<^>>",
					StratagemClass.SUPPORT,
					false
				),
			&"heavy_machine_gun":
				StratagemData.new(
					preload("res://resources/images/heavy_machine_gun.svg"),
					"stratagem_name.heavy_machine_gun",
					"v<^vv",
					StratagemClass.SUPPORT,
					false
				),
			&"hellbomb":
				StratagemData.new(
					preload("res://resources/images/hellbomb.svg"),
					"stratagem_name.hellbomb",
					"v^<v^>v^",
					StratagemClass.COMMON,
					false
				),
			&"hellbomb_portable":
				StratagemData.new(
					preload("res://resources/images/hellbomb_portable.svg"),
					"stratagem_name.hellbomb_portable",
					"v>^^^",
					StratagemClass.SUPPORT,
					true  # B-100 Portable Hellbomb
				),
			&"hive_breaker_drill":
				StratagemData.new(
					preload("res://resources/images/hive_breaker_drill.svg"),
					"stratagem_name.hive_breaker_drill",
					"<^v>vv",
					StratagemClass.COMMON,
					false
				),
			&"hmg_emplacement":
				StratagemData.new(
					preload("res://resources/images/hmg_emplacement.svg"),
					"stratagem_name.hmg_emplacement",
					"v^<>><",
					StratagemClass.DEFENCE,
					false
				),
			&"hover_pack":
				StratagemData.new(
					preload("res://resources/images/hover_pack.svg"),
					"stratagem_name.hover_pack",
					"v^^v<>",
					StratagemClass.SUPPORT,
					true  # LIFT-860 Hover Pack
				),
			&"incendiary_mines":
				StratagemData.new(
					preload("res://resources/images/incendiary_mines.svg"),
					"stratagem_name.incendiary_mines",
					"v<<v",
					StratagemClass.DEFENCE,
					false
				),
			&"jump_pack":
				StratagemData.new(
					preload("res://resources/images/jump_pack.svg"),
					"stratagem_name.jump_pack",
					"v^^v^",
					StratagemClass.SUPPORT,
					false
				),
			&"laser_cannon":
				StratagemData.new(
					preload("res://resources/images/laser_cannon.svg"),
					"stratagem_name.laser_cannon",
					"v<v^<",
					StratagemClass.SUPPORT,
					false
				),
			&"laser_sentry":
				StratagemData.new(
					preload("res://resources/images/laser_sentry.svg"),
					"stratagem_name.laser_sentry",
					"v^>v^>",
					StratagemClass.DEFENCE,
					true  # AVLAS-98 Laser Sentry
				),
			&"machine_gun":
				StratagemData.new(
					preload("res://resources/images/machine_gun.svg"),
					"stratagem_name.machine_gun",
					"v<v^>",
					StratagemClass.SUPPORT,
					false
				),
			&"machine_gun_sentry":
				StratagemData.new(
					preload("res://resources/images/machine_gun_sentry.svg"),
					"stratagem_name.machine_gun_sentry",
					"v^>>^",
					StratagemClass.DEFENCE,
					false
				),
			&"maxigun":
				StratagemData.new(
					preload("res://resources/images/maxigun.svg"),
					"stratagem_name.maxigun",
					"v<>v^^",
					StratagemClass.SUPPORT,
					true  # M-1000 Maxigun
				),
			&"mortar_sentry":
				StratagemData.new(
					preload("res://resources/images/mortar_sentry.svg"),
					"stratagem_name.mortar_sentry",
					"v^>>v",
					StratagemClass.DEFENCE,
					false
				),
			&"one_true_flag":
				StratagemData.new(
					preload("res://resources/images/one_true_flag.svg"),
					"stratagem_name.one_true_flag",
					"v<>>^",
					StratagemClass.SUPPORT,
					true  # CQC-1 One True Flag
				),
			&"orbital_120mm_he_barrage":
				StratagemData.new(
					preload("res://resources/images/orbital_120mm_he_barrage.svg"),
					"stratagem_name.orbital_120mm_he_barrage",
					">>v<>v",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_380mm_he_barrage":
				StratagemData.new(
					preload("res://resources/images/orbital_380mm_he_barrage.svg"),
					"stratagem_name.orbital_380mm_he_barrage",
					">v^^<vv",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_airburst_strike":
				StratagemData.new(
					preload("res://resources/images/orbital_airburst_strike.svg"),
					"stratagem_name.orbital_airburst_strike",
					">>>",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_ems_strike":
				StratagemData.new(
					preload("res://resources/images/orbital_ems_strike.svg"),
					"stratagem_name.orbital_ems_strike",
					">><v",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_gas_strike":
				StratagemData.new(
					preload("res://resources/images/orbital_gas_strike.svg"),
					"stratagem_name.orbital_gas_strike",
					">>v>",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_gatling_barrage":
				StratagemData.new(
					preload("res://resources/images/orbital_gatling_barrage.svg"),
					"stratagem_name.orbital_gatling_barrage",
					">v<^^",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_laser":
				StratagemData.new(
					preload("res://resources/images/orbital_laser.svg"),
					"stratagem_name.orbital_laser",
					">v^>v",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_napalm_barrage":
				StratagemData.new(
					preload("res://resources/images/orbital_napalm_barrage.svg"),
					"stratagem_name.orbital_napalm_barrage",
					">>v<>^",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_precision_strike":
				StratagemData.new(
					preload("res://resources/images/orbital_precision_strike.svg"),
					"stratagem_name.orbital_precision_strike",
					">>^",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_railcannon_strike":
				StratagemData.new(
					preload("res://resources/images/orbital_railcannon_strike.svg"),
					"stratagem_name.orbital_railcannon_strike",
					">^vv>",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_smoke_strike":
				StratagemData.new(
					preload("res://resources/images/orbital_smoke_strike.svg"),
					"stratagem_name.orbital_smoke_strike",
					">>v^",
					StratagemClass.ATTACK,
					false
				),
			&"orbital_walking_barrage":
				StratagemData.new(
					preload("res://resources/images/orbital_walking_barrage.svg"),
					"stratagem_name.orbital_walking_barrage",
					">v>v>v",
					StratagemClass.ATTACK,
					false
				),
			&"patriot_exosuit":
				StratagemData.new(
					preload("res://resources/images/patriot_exosuit.svg"),
					"stratagem_name.patriot_exosuit",
					"<v>^<vv",
					StratagemClass.SUPPORT,
					false
				),
			&"prospecting_drill":
				StratagemData.new(
					preload("res://resources/images/prospecting_drill.svg"),
					"stratagem_name.prospecting_drill",
					"vv<>vv",
					StratagemClass.COMMON,
					false
				),
			&"quasar_cannon":
				StratagemData.new(
					preload("res://resources/images/quasar_cannon.svg"),
					"stratagem_name.quasar_cannon",
					"vv^<>",
					StratagemClass.SUPPORT,
					false
				),
			&"railgun":
				StratagemData.new(
					preload("res://resources/images/railgun.svg"),
					"stratagem_name.railgun",
					"v>v^<>",
					StratagemClass.SUPPORT,
					false
				),
			&"recoilless_rifle":
				StratagemData.new(
					preload("res://resources/images/recoilless_rifle.svg"),
					"stratagem_name.recoilless_rifle",
					"v<>><",
					StratagemClass.SUPPORT,
					false
				),
			&"reinforce":
				StratagemData.new(
					preload("res://resources/images/reinforce.svg"),
					"stratagem_name.reinforce",
					"^v><^",
					StratagemClass.COMMON,
					false
				),
			&"resupply":
				StratagemData.new(
					preload("res://resources/images/resupply.svg"),
					"stratagem_name.resupply",
					"vv^>",
					StratagemClass.COMMON,
					false
				),
			&"rocket_sentry":
				StratagemData.new(
					preload("res://resources/images/rocket_sentry.svg"),
					"stratagem_name.rocket_sentry",
					"v^>><",
					StratagemClass.DEFENCE,
					false
				),
			&"seaf_artillery":
				StratagemData.new(
					preload("res://resources/images/seaf_artillery.svg"),
					"stratagem_name.seaf_artillery",
					">^^v",
					StratagemClass.COMMON,
					false
				),
			&"seismic_probe":
				StratagemData.new(
					preload("res://resources/images/seismic_probe.svg"),
					"stratagem_name.seismic_probe",
					"^^<>vv",
					StratagemClass.COMMON,
					false
				),
			&"shield_generator_pack":
				StratagemData.new(
					preload("res://resources/images/shield_generator_pack.svg"),
					"stratagem_name.shield_generator_pack",
					"v^<><>",
					StratagemClass.SUPPORT,
					false
				),
			&"shield_generator_relay":
				StratagemData.new(
					preload("res://resources/images/shield_generator_relay.svg"),
					"stratagem_name.shield_generator_relay",
					"vv<><>",
					StratagemClass.DEFENCE,
					false
				),
			&"solo_silo":
				StratagemData.new(
					preload("res://resources/images/solo_silo.svg"),
					"stratagem_name.solo_silo",
					"v^>vv",
					StratagemClass.SUPPORT,
					true  # MS-11 Solo Silo
				),
			&"sos_beacon":
				StratagemData.new(
					preload("res://resources/images/sos_beacon.svg"),
					"stratagem_name.sos_beacon",
					"^v>^",
					StratagemClass.COMMON,
					false
				),
			&"spear":
				StratagemData.new(
					preload("res://resources/images/spear.svg"),
					"stratagem_name.spear",
					"vv^vv",
					StratagemClass.SUPPORT,
					false
				),
			&"speargun":
				StratagemData.new(
					preload("res://resources/images/speargun.svg"),
					"stratagem_name.speargun",
					"v>v<^>",
					StratagemClass.SUPPORT,
					true  # S-11 Speargun
				),
			&"sta_x3_wasp_launcher":
				StratagemData.new(
					preload("res://resources/images/sta_x3_w.a.s.p._launcher.svg"),
					"stratagem_name.sta_x3_wasp_launcher",
					"vv^v>",
					StratagemClass.SUPPORT,
					false
				),
			&"stalwart":
				StratagemData.new(
					preload("res://resources/images/stalwart.svg"),
					"stratagem_name.stalwart",
					"v<v^^<",
					StratagemClass.SUPPORT,
					false
				),
			&"sterilizer":
				StratagemData.new(
					preload("res://resources/images/sterilizer.svg"),
					"stratagem_name.sterilizer",
					"v<^v<",
					StratagemClass.SUPPORT,
					true  # TX-41 Sterilizer
				),
			&"super_earth_flag":
				StratagemData.new(
					preload("res://resources/images/super_earth_flag.svg"),
					"stratagem_name.super_earth_flag",
					"v^v^",
					StratagemClass.COMMON,
					false
				),
			&"supply_pack":
				StratagemData.new(
					preload("res://resources/images/supply_pack.svg"),
					"stratagem_name.supply_pack",
					"v<v^^v",
					StratagemClass.SUPPORT,
					false
				),
			&"tectonic_drill":
				StratagemData.new(
					preload("res://resources/images/tectonic_drill.svg"),
					"stratagem_name.tectonic_drill",
					"^v^v^v",
					StratagemClass.COMMON,
					false
				),
			&"tesla_tower":
				StratagemData.new(
					preload("res://resources/images/tesla_tower.svg"),
					"stratagem_name.tesla_tower",
					"v^>^<>",
					StratagemClass.DEFENCE,
					false
				),
			&"upload_data":
				StratagemData.new(
					preload("res://resources/images/upload_data.svg"),
					"stratagem_name.upload_data",
					"<>^^^",
					StratagemClass.COMMON,
					false
				),
			&"warp_pack":
				StratagemData.new(
					preload("res://resources/images/warp_pack.svg"),
					"stratagem_name.warp_pack",
					"v<>v<>",
					StratagemClass.SUPPORT,
					true  # LIFT-182 Warp Pack
				),
		}
